SalesInventory/Controllers/API/ProductApiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SalesInventory.Data.DbContext;
using SalesInventory.Models;
using SalesInventory.Models.DbModels;
using SalesInventory.Models.InputModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SalesInventory.Controllers.API
{
   

    [Route("api/[controller]")]
    [ApiController]

    public class ProductApiController : ControllerBase
    {
        private readonly DbHelper _dbHelper;
        public ProductApiController(DbHelper dbHelper)
        {
            _dbHelper = dbHelper;

        }
        [HttpGet]
        [Route("GenerateRandom")]

        public IActionResult GenerateRandom()
        {
            var random = new Random();
            int randomNumber = random.Next();
            return Ok(randomNumber);
        }

        [HttpGet]
        [Route("GetAllProducts")]
        public IActionResult GetAllProducts()
        {
            var products = _dbHelper.GetAllProducts();
            return Ok(products);
        }

        [HttpGet]
        [Route("GetProductById")]
        public IActionResult GetProductById(int productId)
        {
            var products = _dbHelper.GetProductById(productId);
            return Ok(products);
        }

        [HttpGet]
        [Route("GetAllSalesById")]
        public IActionResult GetAllSalesByProductId(int productId)
        {
            var products = _dbHelper.GetAllSalesByProductId(productId);
            return Ok(products);
        }

        [HttpPost]
        [Route("InsertSales")]
        public IActionResult RecordSales(AddSalesModel addSales)
        {
            
            var products = _dbHelper.GetAllProducts();
            var product = products.FirstOrDefault(p => p.ProductId == addSales.ProductId);
            addSales.TotalAmount = product.Cost * addSales.QuantitySold;
            var dbResponse = _dbHelper.InsertSale(addSales.ProductId, addSales.QuantitySold, addSales.TotalAmount, addSales.SoldBy);
            if(dbResponse == "success")
            {
                return Ok("succesful");

            }
            else
            {
                return BadRequest(dbResponse);
            }

            
        }



    }
}

SalesInventory/Controllers/SalesController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SalesInventory.Data.DbContext;
using SalesInventory.Models;
using SalesInventory.Models.InputModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SalesInventory.Controllers
{
    public class SalesController : Controller
    {
        private readonly DbHelper _dbHelper;

        public SalesController(DbHelper dbHelper )
        {
            _dbHelper = dbHelper;

        }
        public IActionResult RecordSales(int productId)
        {
            ViewBag.ProductSales = _dbHelper.GetAllSalesByProductId(productId);
            ViewBag.ProductId = productId;
            ViewBag.Products = _dbHelper.GetAllProducts();
            ViewBag.GetProductById = _dbHelper.GetProductById(productId);
            return View();
        }

        [HttpPost]
        public IActionResult RecordSales(AddSalesModel addSales)
        {
            var products = _dbHelper.GetAllProducts();
            var product = products.FirstOrDefault(p => p.ProductId == addSales.ProductId);
            var totalAmount = product.Cost * addSales.QuantitySold;
            var insertSale = _dbHelper.InsertSale(addSales.ProductId, addSales.QuantitySold, totalAmount, addSales.SoldBy);
            return RedirectToAction("RecordSales", "Sales", new { productId = product.ProductId });
        }

        [HttpPost]
        public IActionResult ProductSales_Read([DataSourceRequest] DataSourceRequest request, int productId)
        {
            
            
            var data = _dbHelper.GetAllSalesByProductId(productId);
            return Json(data.ToDataSourceResult(request));
        }




    }
}

SalesInventory/Views/Sales/RecordSales.cshtml
@{
    ViewData["Title"] = "Product Sales";
    List<ProductSalesModels> sales = ViewBag.ProductSales;
    var products = ViewBag.GetProductById;
}



<h3>Product Sales</h3>
<br />



@{
    <div class="row">
        <div class="col-6">
            <p id="pName"><strong>Product Name :</strong>@products.ProductName</p>
            <p id="pCategory"><strong>Product Category :</strong> @products.CategoryName</p>
            <p id="pStockAvailable"><strong>Stock Available :</strong> @products.StockAvailable</p>

        </div>
    </div>
}





<br />
<br />
<form @*method="post"*@ @*asp-controller="ProductApi" asp-action="InsertSales"*@ id="myForm">
    <div class="row">
        <div class="col-3">
            <label class="form-label">Quantity Sold</label>
            <input class="form-control" id="QuantitySold" name="QuantitySold">
        </div>
        <div class="col-3">
            <label class="form-label">Sold By</label>
            <input class="form-control" name="SoldBy" id="SoldBy">

        </div>
        <div class="col-3">
            <label class="form-label"></label>
            <input class="col" name="ProductId" style="display:none" value='@ViewBag.ProductId' />
            <button class="btn btn-primary mb-2 form-control" type="submit" id="submit">Record Sales</button>


        </div>


    </div>
</form>

@*<form method="post" asp-controller="Sales" asp-action="RecordSales">
        <div class="row">
            <div class="col-3">
                <label class="form-label">Quantity Sold</label>
                <input class="form-control" id="QuantitySold" name="QuantitySold">
            </div>
            <div class="col-3">
                <label class="form-label">Sold By</label>
                <input class="form-control" name="SoldBy" id="SoldBy">

            </div>
            <div class="col-3">
                <label class="form-label"></label>
                <input class="col" name="ProductId" style="display:none" value='@ViewBag.ProductId' />
                <button class="btn btn-primary mb-2 form-control" type="submit">Record Sales</button>


            </div>


        </div>
    </form>*@


<br />
<br />






<table class="table">
    <tr>
        <th>Product</th>
        <th>Total Amount</th>
        <th>Sold By</th>
        <th>Sold At</th>
        <th>Quantity Sold</th>
    </tr>



    @foreach (var sale in sales)
    {

        <tr>
            <td>@sale.ProductName</td>
            <td>@sale.TotalAmount</td>
            <td>@sale.SoldBy</td>
            <td>@sale.CreatedAt.ToString("dd-MMM-yyyy hh:mm tt")</td>
            <td>@sale.QuantitySold</td>
        </tr>
    }

</table>


</div>

<div>
    @(Html.Kendo().Grid<ProductSalesModels>()
.Name("productSalesGrid")
.Columns(columns =>
{
    columns.Bound(c => c.ProductName).Title("Product Name").Width(190);
    columns.Bound(c => c.TotalAmount).Title("Total Amount").Width(190);
    columns.Bound(c => c.SoldBy).Title("Sold By").Width(190);
    columns.Bound(c => c.CreatedAt).Title("Sold At").Width(190);
    columns.Bound(c => c.QuantitySold).Title("Quantity Sold").Width(190);




    columns.Command(c =>
    {
        c.Edit();
        c.Destroy();
    }).Width(200);



})



.ToolBar(tools => { tools.Create().Text("Add Product Sales Category"); tools.Excel(); tools.Pdf(); })
.Excel(excel => excel
.FileName("ProductSales.xlsx")
.Filterable(true)
)
.Pdf(pdf => pdf
.FileName("ProductSales.pdf")
)
.Scrollable(s => s.Height("auto"))
.Groupable()
.Editable(e => e.Mode(GridEditMode.PopUp))
.Sortable()
.Filterable(f => f.Enabled(true).Operators(o =>
{
    o.ForDate(t =>
    {
        t.Clear();
        t.IsGreaterThan("Start Date");
        t.IsLessThan("End Date");
    });
})
)
.Pageable(pageable => pageable
.Refresh(true)
.PageSizes(true)
.ButtonCount(3).PageSizes(new int[] { 10, 100, 1000 }))
.DataSource(dataSource => dataSource
.Ajax()
.PageSize(100)
.Model(m => m.Id(p=>p.ProductId))
.Events(events =>
{
    events.Error("error_handler");
})
.Read(read => read.Action("ProductSales_Read", "Sales", new { productId = @ViewBag.ProductId}))
.Create(c => c.Action("User_Add", "Users"))
.Update(c => c.Action("User_Update", "Users"))
.Destroy(c => c.Action("User_Update", "Users"))



)
)
</div>

@section Scripts {
    <script>

        //$(document).ready(function () {
        //    $.ajax({
        //        url: `/Api/ProductApi/GetProductById?productId=${productId}`,
        //        type: 'GET',
        //        dataType: 'json',

        //        success: function (data, status, xhr) {   // success callback function
        //            console.log("All Products By Id", data);
        //            var m = $('#Ainz');
        //            data.forEach(function (dataRow) {
        //                var tableRow = `
        //                <tr>
        //                    <td> ${dataRow.productName}</td>
        //                    <td> ${dataRow.categoryName}</td>
        //                    <td> ${dataRow.stockAvailable}</td>

        //                </tr>
        //                `

        //                                        m.append(tableRow);
        //            });


        //                //$("#m").append("<td>"+data.productName+ "</td">);

        //            //})
        //            //$('p').append(data.productName + ' ' + data.middleName + ' ' + data.lastName);
        //        },
        //        error: function (jqXhr, textStatus, errorMessage) { // error callback
        //            $('p').append('Error: ' + errorMessage);
        //        }




        //    });




        /*  })*/
        $(document).ready(function () {
            $('#myForm').submit(function (e) {
                e.preventDefault();

                var requestPayload = {
                    "QuantitySold": $('#QuantitySold').val(),
                    "SoldBy": $('#SoldBy').val(),
                    "Productid" : '@ViewBag.ProductId'
                };

                $.ajax({
                    url: `/Api/ProductApi/InsertSales`,
                    type: 'POST',
                    data: JSON.stringify(requestPayload),
                    contentType : 'application/json',
                    success: function (data, status, xhr) {
                        if (data == "succesful") {
                            alert("Product sales recorded succesfully");
                            location.reload();
                            
                        }
                        console.log(data);
                    },
                    error: function ( error) {
                        alert(error.responseText);

                            }
                    });
            });


        })




    </script>
     <script>
        function error_handler(e) {
            try {
                var errorMessage = "";
                if (e && e.xhr) {
                    var errorMessage = e.xhr.responseText;
                }



                if (errorMessage) {
                    alert(errorMessage);
                }



            } catch (e) {
                console.log(e);
                alert("Oops! An error occurred while processing your request");
            }
        }


    </script>

}